version: '3'

services:
    elasticsearch:
        build:  ./elasticsearch     #on va chercher le dockerfile dans ce répertoire
        container_name: elasticsearch
        environment:
            - "discovery.type=single-node"
        networks:
            - net    #réseau commun à tous les contenneurs
        volumes:
            - esdata:/usr/share/elasticsearch/data

        
    kibana:
        build:  ./kibana
        container_name: kibana
        environment: 
            SERVER_NAME : kibana
            ELASTICSEARCH_URL : http://elasticsearch:9200
        networks:
            - net

    proxy:
        build:  ./nginx
        container_name: nginx
        ports:
            - "8080:80"
        networks:
            - net

networks:
    net:

volumes:
    esdata:
        driver: local